FROM eclipse-temurin:23-jdk AS builde

WORKDIR /app

RUN  apt-get update && apt-get install -y maven

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:23-jre

WORKDIR /app

COPY --from=builde /app/target/*.jar app.jar

EXPOSE 8080

ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
ENV JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
ENV RENIEC_API_URL=${RENIEC_API_URL}
ENV RENIEC_API_TOKEN=${RENIEC_API_TOKEN}


ENTRYPOINT ["java", "-jar", "app.jar"]